export default {
	0: 'TYPE_FIRSTBLOCK',
	276: 'TYPE_TRANSFER',
	293: 'TYPE_CREATEUSER',
	264: 'TYPE_TASK',
	279: 'TYPE_LOCK_FUND',
	296: 'TYPE_UPDATESYSTEM',
	280: 'TYPE_CREATE_LOCK_FUND',
	288: 'TYPE_CREATE_CONTRACT'
};